<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $table = DB::table('categories');


        // Provided list of categories
        $data = [
            ['Pop'],
            ['Rock'],
            ['Hip hop'],
            ['Country'],
            ['Jazz'],
            ['Blues'],
            ['Electronic'],
            ['Classical'],
            ['R&B'],
            ['Reggae'],
            ['Folk'],
            ['Alternative'],
            ['Metal'],
            ['Punk'],
            ['Indie'],
            ['Gospel'],
            ['Dance'],
            ['Funk'],
            ['Soul'],
            ['Rap'],
            ['Ska'],
            ['EDM (Electronic Dance Music)'],
            ['World'],
            ['Ambient'],
            ['Reggaeton'],
            ['Dubstep'],
            ['Techno'],
            ['House'],
            ['Trance'],
            ['Latin'],
            ['Americana'],
            ['Grunge'],
            ['Celtic'],
            ['Ballad'],
            ['Acoustic'],
            ['Synth-pop'],
            ['Opera'],
            ['Motown'],
            ['Bollywood'],
            ['J-pop'],
            ['K-pop'],
            ['Instrumental'],
            ['Baroque'],
            ['Salsa'],
            ['Bossa Nova'],
            ['Hard Rock'],
            ['Heavy Metal'],
            ['Emo'],
            ['Psychedelic'],
            ['Disco'],
            ['Bluegrass'],
            ['Funk Rock'],
            ['Afrobeat'],
            ['Chamber Music'],
            ['Country Rock'],
            ['Dream Pop'],
            ['Electro Swing'],
            ['Garage Rock'],
            ['Glam Rock'],
            ['Jive'],
            ['New Wave'],
            ['Post-punk'],
            ['Shoegaze'],
            ['Surf Rock'],
            ['Tango'],
            ['Trip hop'],
            ['Zydeco'],
            ['Ambient House'],
            ['Breakbeat'],
            ['Cajun'],
            ['Chanson'],
            ['Downtempo'],
            ['Hardstyle'],
            ['IDM (Intelligent Dance Music)'],
            ['Jungle'],
            ['Mambo'],
            ['Merengue'],
            ['Neoclassical'],
            ['New Age'],
            ['Nu Metal'],
            ['Polka'],
            ['Progressive Rock'],
            ['Rockabilly'],
            ['Smooth Jazz'],
            ['Swing'],
            ['Vaporwave'],
            ['Acid Jazz'],
            ['Big Band'],
            ['Blue-eyed Soul'],
            ['Contemporary Christian'],
            ['Country Blues'],
            ['Electro-funk'],
            ['Free Jazz'],
            ['Gypsy Jazz'],
            ['Latin Jazz'],
            ['Noise Rock'],
            ['Nu-disco'],
            ['Post-rock'],
            ['Samba'],
            ['Space Rock'],
            ['Folk Rock'],
            ['Electro House'],
            ['Trap'],
            ['Chillout'],
            ['Drum and Bass'],
            ['Fado'],
            ['Industrial'],
            ['Minimal'],
            ['Power Metal'],
            ['Ragtime'],
            ['Rock and Roll'],
            ['Swing Jazz'],
            ['Tropical House'],
            ['Boogie-woogie'],
            ['Country Pop'],
            ['Death Metal'],
            ['Dub'],
            ['Freestyle'],
            ['Gothic Metal'],
            ['Nu Jazz'],
            ['Soul Jazz'],
            ['Symphony'],
            ['Thrash Metal'],
            ['Vocal Jazz'],
            ['Zouk'],
            ['Bhangra'],
            ['Chiptune'],
            ['Electropop'],
            ['Grindcore'],
            ['Hardcore Punk'],
            ['Jazz Fusion'],
            ['Krautrock'],
            ['Reggae Fusion'],
            ['Rocksteady'],
            ['Space Ambient'],
            ['Swing Revival'],
            ['Tech House'],
            ['Tribal House'],
            ['Yacht Rock'],
            ['Alternative Rock'],
            ['Barbershop'],
            ['Cowpunk'],
            ['Dark Ambient'],
            ['Eurodance'],
            ['Glam Metal'],
            ['Happy Hardcore'],
            ['Latin Pop'],
            ['Math Rock'],
            ['Progressive Metal'],
            ['Screamo'],
            ['Stoner Rock'],
            ['Symphonic Metal'],
            ['Tropicalia']
        ];

        Schema::disableForeignKeyConstraints();
        $table->truncate();

        foreach ($data as $datum) {
            $table->insert([
                'name' => $datum[0],
            ]);
        }
        Schema::enableForeignKeyConstraints();
    }
}
